export const productReponse = {
  product_id: true,
  category_id: true,
  company_id: true,
  product_type: true,
  sku: true,
  title: true,
  subtitle: true,
  description: true,
  url_banner: true,
  active: true,
  combo: true,
  amount_min_sale: true,
  amount_max_sale: true,
  highlighted: true,
  order_on_menu: true,
  for_sale: true,
  discount: true,
};
